version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: ./Dev.Dockerfile
    command: '/app/scripts/docker/local-run.sh'
    ports:
      - '8080:8080'
      - '9229:9229'
    depends_on:
      - db
    env_file: .env.example
    volumes:
      - './src:/app/src'
      - './scripts/db:/app/scripts/db'
    networks:
      - node-network

  db:
    image: mongo:4.4.6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

  client:
    build:
      context: ../dashboard-creator-client
      dockerfile: ../dashboard-creator-client/Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - '../dashboard-creator-client/src:/usr/src/app/src'
    networks:
      - node-network

  db-api:
    build:
      context: ../db-api
      dockerfile: ../db-api/dev.Dockerfile
    command: npm run watch-node
    ports:
      - '8082:3000'
    env_file: ../db-api/.env
    volumes:
      - '../db-api:/usr/src/node-app'
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
