const DAPP_ANALYTICS_NETWORKS = {
  'aleph-zero': {
    type: 'substrate',
    rpcEndpoint: 'https://aleph-zero.api.onfinality.io/public',
    ss58Network: 'substrate',
    gatewayUrl: 'https://v2.archive.subsquid.io/network/aleph-zero',
    rpcIngestionDisabled: 'true',
    traces: false,
  },
  'arbitrum-one': {
    type: 'evm',
    rpcEndpoint: 'not found yet',
    ss58Network: 'irrelevant',
    gatewayUrl: 'https://v2.archive.subsquid.io/network/arbitrum-one',
    rpcIngestionDisabled: 'true',
    traces: true,
  },
  'arbitrum-nova': {
    type: 'evm',
    rpcEndpoint: 'not found yet',
    ss58Network: 'irrelevant',
    gatewayUrl: 'https://v2.archive.subsquid.io/network/arbitrum-nova',
    rpcIngestionDisabled: 'true',
    traces: true,
  },
  astar: {
    type: 'substrate',
    rpcEndpoint: 'https://astar.api.onfinality.io/public',
    ss58Network: 'astar',
    gatewayUrl: 'https://v2.archive.subsquid.io/network/astar-substrate',
    rpcIngestionDisabled: 'true',
    traces: false,
  },
  avalanche: {
    type: 'evm',
    rpcEndpoint: 'not found yet',
    ss58Network: 'irrelevant',
    gatewayUrl: 'https://v2.archive.subsquid.io/network/avalanche-mainnet',
    rpcIngestionDisabled: 'true',
    traces: true,
  },
  moonbeam: {
    type: 'evm',
    rpcEndpoint: 'https://moonbeam.api.onfinality.io/public',
    ss58Network: 'irrelevant',
    gatewayUrl: 'https://v2.archive.subsquid.io/network/moonbeam-mainnet',
    rpcIngestionDisabled: 'true',
    traces: true,
  },
  optimism: {
    type: 'evm',
    rpcEndpoint: 'not found yet',
    ss58Network: 'irrelevant',
    gatewayUrl: 'https://v2.archive.subsquid.io/network/optimism-mainnet',
    rpcIngestionDisabled: 'true',
    traces: true,
  },
};

export default DAPP_ANALYTICS_NETWORKS;
